/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author Ida Bagus Mahendra
 */
public class login extends javax.swing.JFrame {

   public String usr;//membuat variabel public String
    public int lvl=0; //membuat variabel public int
    public int no=0;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
    
    public void uslog()
    {
        String log = field1.getText();//mengambil nilai dari field 1
        String pas = field2.getText();//mengambil nilai dari field 2
        try
        {
            Connection c = KoneksiDB.getkoneksi();//membuat koneksi ke database
            Statement s = c.createStatement();//membuat statement sesuai koneksi
            String sql= "SELECT * FROM user WHERE username ='"+log+"' AND password='"+pas+"' ";//menseleksi nilai pada tabel user
            ResultSet rs = s.executeQuery(sql);//menyimpan hasil eksekusi query sql pada rs
            
            while(rs.next())//membuat perulangan untuk setiap nilai rs
            {
                lvl=rs.getInt(4);//digunakan untuk mengambil nilai dari setiap perulangan result set baris 4
                usr=rs.getString(1);//digunakan untuk mengambil nilai dari setiap perulangan result set baris 1
            }
            
           
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);//menampilkan pesan error
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        field1 = new javax.swing.JTextField();
        judul = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        field2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id.setText("Username");

        password.setText("Password");

        field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field1ActionPerformed(evt);
            }
        });

        judul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        judul.setText("LOGIN");

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id)
                            .addComponent(password))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(login)
                                .addGap(18, 18, 18)
                                .addComponent(reset))
                            .addComponent(field2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(judul)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(judul)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(field2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(reset))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        field1.setText("");
        field2.setText("");
    }//GEN-LAST:event_resetActionPerformed
    
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
            uslog();//memanggil method uslog()
            
            if(lvl == 1)// lvl user 1 manager
            {
                try
                {
                    Connection c = KoneksiDB.getkoneksi();//membuat koneksi ke database
                    Statement s = c.createStatement();//membuat statement sesuai koneksi
                    String loged= "SELECT no_login FROM login";
                    ResultSet t = s.executeQuery(loged);
                    while(t.next())
                    {
                       int ambil = t.getInt("no_login");    
                       no =  ambil;
                    }
                    String userlogin = "INSERT INTO login(username,tanggal,waktu,level,kondisi) values('"+usr+"',now(),now(),'"+lvl+"','1')";
                    s.executeUpdate(userlogin);
                    
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this, e);//menampilkan pesan error
                }

                JOptionPane.showMessageDialog(this,"Login Sukses, \n"+"Hallo "+usr);//menampilkan pesan ke layar
                utama menu = new utama();//membuat object dari class utama
                menu.hakmanager();//menampilkan method hakmanager dari class menu
                menu.show();//menampilkan kelas utama
                this.dispose();//membuang kelas ini
            }
            else if(lvl == 2)//lvl user kasir
            {
                try
                {
                    Connection c = KoneksiDB.getkoneksi();//membuat koneksi ke database
                    Statement s = c.createStatement();//membuat statement sesuai koneksi
                    String loged= "SELECT no_login FROM login";
                    ResultSet t = s.executeQuery(loged);
                    while(t.next())
                    {
                       int ambil = t.getInt("no_login");    
                       no =  ambil;
                    }
                    String userlogin = "INSERT INTO login(username,tanggal,waktu,level,kondisi) values('"+usr+"',now(),now(),'"+lvl+"','1')";
                    s.executeUpdate(userlogin);
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this, e);//menampilkan pesan error
                }
                JOptionPane.showMessageDialog(this,"Login Sukses, \n"+"Hallo "+usr);//menampilkan pesan ke layar
                utama menu = new utama();//membuat object dari class utama
                menu.hakkasir();//menampilkan method hakkasir dari class menu
                menu.show();//menampilkan kelas utama
                this.dispose();//membuang kelas ini
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Login Gagal! \n"+"Data Tidak Ditemukan. ");//menampilkan pesan gagal
            }
    }//GEN-LAST:event_loginActionPerformed

    private void field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField field1;
    private javax.swing.JPasswordField field2;
    private javax.swing.JLabel id;
    private javax.swing.JLabel judul;
    public javax.swing.JButton login;
    private javax.swing.JLabel password;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
